---
- hosts: vagrant-gorillalogic
  become: true

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      become: yes

  tasks:
    - name: Run apt-update and install Docker-CE and vagrant on host
      apt:
        pkg:
        - git
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - vagrant
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Clone and Update deploy repo on vagrant host
      ansible.builtin.git:
        repo: 'https://github.com/Richzendy/timeoff-management-deploy'
        dest: /root/timeoff-management-deploy
        update: yes
        version: master

    - name: update timeoff-management-app repo from master
      command: git pull origin master 
      args:
        chdir: "/root/timeoff-management-deploy/timeoff-management-application"

    - name: Execute vagrant up
      command: vagrant up      
      args:
        chdir: /root/timeoff-management-deploy

    - name: Rebuild Docker Container
      command: vagrant reload      
      args:
        chdir: /root/timeoff-management-deploy


