---
- hosts: vagrant-gorillalogic
  become: true

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      become: yes

  tasks:
    - name: Accept virtualbox-ext-pack seen license
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: seen

    - name: Accept virtualbox-ext-pack select license
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Run apt-update and install virtualbox virtualbox-ext-pack
      apt:
        pkg:
        - virtualbox
        - virtualbox-ext-pack
        - vagrant
        update_cache: yes
        cache_valid_time: 3600

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: Clone and Update deploy repo on vagrant host
      ansible.builtin.git:
        repo: 'https://github.com/Richzendy/timeoff-management-deploy'
        dest: /root/
        update: yes
        single_branch: yes
        version: master


