---
- hosts: vagrant-gorillalogic
  become: true

  tasks:

  - name: Run apt-update and install virtualbox virtualbox-ext-pack
    apt:
      name: virtualbox virtualbox-ext-pack
      update_cache: yes
      cache_valid_time: 3600

  - name: Reboot host and wait for it to restart
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami


