version: '3'
services:
  ci-cd:
    build:
      context: .
      args:
        - SSH_PRIVATE_KEY
    ports:
      - "8000:8080"
    entrypoint:
     - ./entrypoint.sh
    volumes:
        - ./jenkins_home:/var/jenkins_home
